# Spam filtering using LR, SVM, NN and Decision trees

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/emails.csv


# Importing necessary packages

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import NearestNeighbors
from sklearn import tree

# Reading Data

In [3]:
data=pd.read_csv('/kaggle/input/emails.csv')

# Data  Preprocessing

In [4]:
data['text'].replace({'Subject:': ''}, inplace=True, regex=True)
X=data['text']
y=data['spam']
vectorizer=CountVectorizer()
X = vectorizer.fit_transform(X)
print(X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [4 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


# Splitting Data

In [5]:
X_train,X_test,Y_train,Y_test=train_test_split(X, y, test_size = 0.2, random_state = 0)

# Initiating models

In [6]:
lr=LogisticRegression()
nb=GaussianNB()
svm=SVC(kernel='rbf')
nn=NearestNeighbors(n_neighbors=2, algorithm='ball_tree')
dt=tree.DecisionTreeClassifier()

# Training all 4 models

In [7]:
lr.fit(X_train,Y_train)
# nb.fit(X_train,Y_train)
svm.fit(X_train,Y_train)
nn.fit(X_train,Y_train)
dt.fit(X_train,Y_train)

/opt/conda/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/opt/conda/lib/python3.6/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/opt/conda/lib/python3.6/site-packages/sklearn/neighbors/base.py:216: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: "


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

# Prediction step

In [8]:
lr_predicted=lr.predict(X_test)
svm_predicted=svm.predict(X_test)
nn_predicted=nn.kneighbors(X_test)
dt_predicted=dt.predict(X_test)

# Classification arror for the 4 algos

In [9]:
lr_cls_report=classification_report(Y_test,lr_predicted)
svm_cls_report=classification_report(Y_test,svm_predicted)
# nb_cls_report=classification_report(Y_test,nb_predicted)
dt_cls_report=classification_report(Y_test,dt_predicted)
print("Logistic regression : "+lr_cls_report)
print("SVM : "+svm_cls_report)
# print("Naive Bayes : "+nb_cls_report)
print("Decision tree : "+dt_cls_report)

Logistic regression :               precision    recall  f1-score   support

           0       0.99      0.99      0.99       885
           1       0.98      0.97      0.97       261

    accuracy                           0.99      1146
   macro avg       0.98      0.98      0.98      1146
weighted avg       0.99      0.99      0.99      1146

SVM :               precision    recall  f1-score   support

           0       0.79      1.00      0.88       885
           1       1.00      0.10      0.19       261

    accuracy                           0.80      1146
   macro avg       0.90      0.55      0.54      1146
weighted avg       0.84      0.80      0.72      1146

Decision tree :               precision    recall  f1-score   support

           0       0.96      0.97      0.97       885
           1       0.89      0.88      0.88       261

    accuracy                           0.95      1146
   macro avg       0.93      0.92      0.93      1146
weighted avg       0.95      0

## All 4 algos have done ok but LR has achieved the best performance. You'll NB algo is commenting because it needs more memory resources(run on aws sagemaker) as compared the algos shown here. So, although NB is known to be the best algo for spam filtering, as per the code run above, it requires more resources. Don't know why? If you know, please comment/modify the code and let me know.